@DogApp.API_HostAddress = https://localhost:7117

GET {{DogApp.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{DogApp.API_HostAddress}}/track/CreateTrack
Content-Type: application/json

{
  
}

###
