
@startuml Dele Bane (Brief)
title Dele bane
legend top
**Sporbarhed**


|Artefakt| Navn |
|UC| Dele Bane|
|**SSD**| **Dele Baner** |
|OC| Dele Baner|
|SD| Share Track |
end legend
!theme Dracula from Dokumentation\Scenarier\Baner\Development View\DCD\

actor "Auth. Bruger" as Bruger
participant System
$PlainMessage(Bruger, System, Tilgår System)
$PlainReturnMessage(Bruger,System,Viser inputside(Bane))
$PlainMessage(Bruger, System, Vælg bane)

loop indtil bruger afslutter 
$PlainMessage(Bruger, System, Vælg Bruger)
$PlainMessage(System, System, Registrer valg)
end
$PlainMessage(Bruger, System, Oversigt over valg)
$PlainMessage(Bruger, Bruger, Del)
$PlainMessage(Bruger, System, Bekræftelse)


@enduml