@startuml Opretter Bane
title Opretter Bane
legend top
**Sporbarhed**

|Artefakt| Navn |
|UC| Opretter Bane|
|**SSD**| **Opretter Baner** |
|OC| Opretter Baner|
|SD| Create Track |
end legend
!theme Dracula from Dokumentation\Scenarier\Baner\Development View\DCD\

actor "Auth. Bruger" as Bruger
participant System as sys

$PlainMessage(Bruger, sys, Tilgår System)
$PlainReturnMessage(Bruger, sys, Viser inputside)
$PlainMessage(Bruger, sys, Vælger banens sværhedsgrad)
$PlainMessage(Bruger, sys, Opretter Bane)
$PlainReturnMessage(Bruger, sys, Viser "Opret Bane" inputside)

loop indtil bruger afslutter
$PlainMessage(Bruger, sys, Placerer skilte; pile og øvrige elementer)
$PlainMessage(sys, sys, Registrer placering)
end

$PlainMessage(Bruger, sys, Afslutter opret bane )
$PlainReturnMessage(Bruger, sys, bekræftelses besked)

@enduml