@startuml SeBane 
title Se Bane\nSSD
!theme Dracula from Dokumentation\Scenarier\Baner\Development View\DCD\

actor Bruger
participant System 
$PlainMessage(Bruger, System,Tilgår System)
$PlainReturnMessage(Bruger, System,Viser inputside(Bane))
$PlainMessage(Bruger, System, Vælg bane)
$PlainReturnMessage(Bruger, System,Viser bane)


@enduml