@startuml Overblik
title **Baner Scenariet**
!theme Dracula from Dokumentation\Scenarier\Baner\Development View\DCD\


!$Green = '#50fa7b'
!$Orange = '#ffb86c'
!$Purple = '#bd93f9'
!$Red = '#ff5555'
!$Yellow = '#f1fa8c'
 

package "Logical View" {
    package "Usecase Diagram"{
        component UC_Diagram        $Green
    }

    package "Misbrugstilfælde"{
        component MBT_OpretterBaner $Red
    }
    
    package "Use Cases" as UseCases{
        component UC_OpdaterBane    $Green
        component UC_OpretterBane   $Green
        component UC_SeBane         $Green
        component UC_SletBane       $Green
        component UC_DeleBane       $Green
        component UC_SeAlleBaner    $Red
    }
    package Wireframes 
    package "System Sequence Diagram"{
        component ssd_Delebane      $Green
        component ssd_OpdaterBane   $Green
        component ssd_OpretterBane  $Green
        component ssd_SletBane      $Green
        component ssd_SeBane        $Green 
        component ssd_SeAlleBaner   $Green
    }
}

package "Development View"{
    package "Database" as DB {
        [Entity Model] $Green
    }
    package "Design class diagram" as DCDpackage{
        [DCD] $Yellow
    }
    package "Operation Contracts"{
        component OC_OpdaterBane    $Green
        component OC_Delerbane      $Green
        component OC_OpretterBane   $Green
        component OC_SletterBane    $Green
        component OC_SeBane         $Green
        component OC_SeAlleBaner    $Red
    }

    package "Domæne Model" as DM {
        component Domænemodel           $Green
    }

    package "Object Model" as OM {
        component ObjectModel           $Green
    }

    package "Sequence Diagram" as SD  {
        package "Se Bane SD'er" as OpdaterBaneSD {
            component SD_ViewOneTrack   $Green
            component SD_ViewAllTracks  $Green
            component SD_CreateTrack    $Green
            component SD_DeleteTrack    $Green
            component SD_ShareTrack     $Red
            component SD_UpdateTrack    $Green
        }
    }
}

package "Physical View"{

}
package "Process View"{
    
}

DCDpackage          <-[thickness=3]-    DB                  $Green
DCDpackage          -[thickness=3]->    DM                  $Green
DM                  -[thickness=3]->    OM                  $Green
UC_Diagram          <-[thickness=3]u-   UseCases            $Green
OC_OpdaterBane      --[thickness=3]->   ssd_OpdaterBane     $Green
OC_SeBane           --[thickness=3]->   ssd_SeBane          $Green
OC_Delerbane        -[thickness=3]->    ssd_Delebane        $Green
OC_OpretterBane     --[thickness=3]->   ssd_OpretterBane    $Green
OC_SletterBane      --[thickness=3]u->  ssd_SletBane        $Green
ssd_Delebane        -[thickness=3]->    UC_DeleBane         $Green
ssd_OpdaterBane     --[thickness=3]->   UC_OpdaterBane      $Green
ssd_SletBane        -[thickness=3]->    UC_SletBane         $Green
ssd_OpretterBane    -[thickness=3]->    UC_OpretterBane     $Green
ssd_SeBane          -[thickness=3]->    UC_SeBane           $Green
SD_ViewOneTrack     -[thickness=3]->    ssd_SeBane          $Green
SD_ViewOneTrack     -[thickness=3]->    OC_SeBane           $Green
SD_ViewAllTracks    -[thickness=3]->    OC_SeAlleBaner      $Red
SD_ViewAllTracks    -[thickness=3]->    ssd_SeAlleBaner     $Green
OC_SeAlleBaner      -[thickness=3]->    ssd_SeAlleBaner     $Red
ssd_SeAlleBaner     -[thickness=3]->    UC_SeAlleBaner      $Red
SD_CreateTrack      -[thickness=3]->    OC_OpretterBane     $Green
SD_CreateTrack      -[thickness=3]->    ssd_OpretterBane    $Green
SD_ShareTrack       -[thickness=3]->    OC_Delerbane        $Red
SD_UpdateTrack      -[thickness=3]->    OC_OpdaterBane      $Green
SD_DeleteTrack      -[thickness=3]->    OC_SletterBane      $Green
SD_ShareTrack       -[thickness=3]->    ssd_Delebane        $Red
SD_UpdateTrack      -[thickness=3]->    ssd_OpdaterBane     $Green
SD_DeleteTrack      -[thickness=3]->    ssd_SletBane        $Green
MBT_OpretterBaner   -[thickness=3]->    UC_OpretterBane     $Red
footer Overblik over projektet
@enduml