@startuml Overblik
title **Baner Scenariet**
!theme Dracula from Dokumentation\Scenarier\Baner\Development View\DCD\


!$Green = '#50fa7b'
!$Orange = '#ffb86c'
!$Purple = '#bd93f9'
!$Red = '#ff5555'
!$Yellow = '#f1fa8c'
 

package "Logical View" {
    package "Usecase Diagram"{
        component UC_Diagram        $Yellow
    }

    package "Use Cases" as UseCases{
        component UC_OpdaterBane    $Yellow
        component UC_OpretterBane   $Yellow
        component UC_SeBane         $Yellow
        component UC_SletBane       $Yellow
        component UC_DeleBane       $Yellow
        component UC_SeAlleBaner    $Red
    }
    package Wireframes 
    package "System Sequence Diagram"{
        component ssd_Delebane      $Yellow
        component ssd_OpdaterBane   $Yellow
        component ssd_OpretterBane  $Yellow
        component ssd_SletBane      $Yellow
        component ssd_SeBane        $Yellow 
        component ssd_SeAlleBaner   $Red
    }
}

package "Development View"{
    package "Database" as DB {
        [Entity Model] $Yellow
    }
    package "Design class diagram" as DCDpackage{
        [DCD] $Yellow
    }
    package "Operation Contracts"{
        component OC_OpdaterBane    $Yellow
        component OC_Delerbane      $Yellow
        component OC_OpretterBane   $Yellow
        component OC_SletterBane    $Yellow
        component OC_SeBane         $Yellow
        component OC_SeAlleBaner    $Red
    }

    package "Domæne Model" as DM {
        component Domænemodel           $Yellow
    }

    package "Object Model" as OM {
        component ObjectModel           $Yellow
    }

    package "Sequence Diagram" as SD  {
        package "Se Bane SD'er" as OpdaterBaneSD {
            component SD_ViewOneTrack   $Yellow
            component SD_ViewAllTracks  $Green
            component SD_CreateTrack    $Green
            component SD_DeleteTrack    $Red
            component SD_ShareTrack     $Red
            component SD_UpdateTrack    $Red
        }
    }
}

package "Physical View"{

}
package "Process View"{
    
}

DCDpackage          <-[thickness=3]-    DB                  $Yellow
DCDpackage          -[thickness=3]->    DM                  $Yellow
DM                  -[thickness=3]->    OM                  $Yellow
UC_Diagram          <-[thickness=3]u-   UseCases            $Yellow
OC_OpdaterBane      --[thickness=3]->   ssd_OpdaterBane     $Yellow
OC_SeBane           --[thickness=3]->   ssd_SeBane          $Yellow
OC_Delerbane        -[thickness=3]->    ssd_Delebane        $Yellow
OC_OpretterBane     --[thickness=3]->   ssd_OpretterBane    $Yellow
OC_SletterBane      --[thickness=3]u->  ssd_SletBane        $Yellow
ssd_Delebane        -[thickness=3]->    UC_DeleBane         $Yellow
ssd_OpdaterBane     --[thickness=3]->   UC_OpdaterBane      $Yellow
ssd_SletBane        -[thickness=3]->    UC_SletBane         $Yellow
ssd_OpretterBane    -[thickness=3]->    UC_OpretterBane     $Yellow
ssd_SeBane          -[thickness=3]->    UC_SeBane           $Yellow
SD_ViewOneTrack     -[thickness=3]->    ssd_SeBane          $Green
SD_ViewOneTrack     -[thickness=3]->    OC_SeBane           $Green
SD_ViewAllTracks    -[thickness=3]->    OC_SeAlleBaner      $Red
SD_ViewAllTracks    -[thickness=3]->    ssd_SeAlleBaner     $Red
OC_SeAlleBaner      -[thickness=3]->    ssd_SeAlleBaner     $Red
ssd_SeAlleBaner     -[thickness=3]->    UC_SeAlleBaner      $Red
SD_CreateTrack      -[thickness=3]->    OC_OpretterBane     $Yellow
SD_CreateTrack      -[thickness=3]->    ssd_OpretterBane    $Yellow
SD_ShareTrack       -[thickness=3]->    OC_Delerbane        $Red
SD_UpdateTrack      -[thickness=3]->    OC_OpdaterBane      $Red
SD_DeleteTrack      -[thickness=3]->    OC_SletterBane      $Red
SD_ShareTrack       -[thickness=3]->    ssd_Delebane        $Red
SD_UpdateTrack      -[thickness=3]->    ssd_OpdaterBane     $Red
SD_DeleteTrack      -[thickness=3]->    ssd_SletBane        $Red

footer Overblik over projektet
@enduml